### ISSUE TITLE
Recognize array insertion, deletion, and reordering

### ISSUE THREAD

**Issue by andreastkdf** [dbohdan/jsonwatch#1]
First of all congrats for the great work!

Is there an option to ignore changes in json order when doing a jsonwatch. For my application I want to watch an json from an url containing elements but do not consider a change in order as a differenceof the json output.

**Comment by dbohdan** [comment]
>First of all congrats for the great work!

Thanks!

>Is there an option to ignore changes in json order when doing a jsonwatch.

What do you mean by "JSON order"? Could you give me an example of data where this happens and the `jsonwatch` output for it? `jsonwatch` is definitely supposed to treat JSON objects as unordered, i.e., it should not consider `{"a": 1, "b": 2}` becoming `{"b": 2, "a": 1}` a change. If it does, that's a bug.

**Comment by andreastkdf** [comment]
Thank you for your answer. My question wasn't clear enough. Here is one example:
data: 
`[{
    "ID": 123006,
    "Descritption": "test1",
    "ContentID": 0,
    "Name": "title",
    "Date": "2018-04-06T09:00:00"},
   {
    "ID": 123007,
    "Descritption": "test1",
    "ContentID": 0,
    "Name": "title",
    "Date": "2018-03-06T09:35:00"}
]` 
`jsonwatch` is looking for changes, and works perfectly when data is changed in one of the entries,
BUT when an New id is added (my api response orders the IDs by DATE) so a new entry will come like this : 
`[
   {
    "ID": 123008,
    "Descritption": "test1",
    "ContentID": 0,
    "Name": "title",
    "Date": "2018-04-09T09:35:00"}
{
    "ID": 123006,
    "Descritption": "test1",
    "ContentID": 0,
    "Name": "title",
    "Date": "2018-04-06T09:00:00"},
   {
    "ID": 123007,
    "Descritption": "test1",
    "ContentID": 0,
    "Name": "title",
    "Date": "2018-04-02T09:35:00"}
]` 
 the output of `jsonwatch` is that the + for the new entry, but it considers that : 
` .1.ID: 123007 -> 123006` etc.. 
So the question I have is it possible to trigger a change only for edit/add and to ignore changes on the "order" of the node of an entry.

I hope it's more precise like this.

Thank you in advance for your help.
Best

**Comment by dbohdan** [comment]
Okay, now it is clear to me what you mean. You want jsonwatch to be able to recognize array insertions, deletions, and changes in element order. It would make the diffs less noisy by showing that
*  the <i>N</i>th element was inserted or deleted instead of how elements _N_ through last changed;
* elements _N_ and _M_ switched their places instead of the modifications to the <i>N</i>th and the <i>M</i>th element.

This is not currently implemented, but it would be useful functionality. I'm putting it on my TODO list.

It may take a while before I get to working on this, however. What you can do for now is preprocess your JSON before feeding it to jsonwatch so that the new elements come last. E.g., if your JSON is just an array sorted as in your example, you can reverse it with [jq](https://stedolan.github.io/jq/manual/).

**Comment by andreastkdf** [comment]
Thank you!

**Comment by dbohdan** [comment]
You're welcome! Tell me if you have any problems with the jq approach.

**Comment by dbohdan** [comment]
Array comparison using a version of the [`diff` algorithm](https://en.wikipedia.org/wiki/Diff#Algorithm) has been implemented in 046c34c9983d851e0e2db55050493af2c35097d4.  It will be in the next release.
